CREATE TABLE roles (
    id INT NOT NULL PRIMARY KEY,
    rolename VARCHAR(50) NOT NULL 
);

CREATE TABLE users_check (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    isActivated BOOLEAN DEFAULT FALSE,
    roleId INT FOREIGN KEY REFERENCES roles(id)
);

